### ISSUE TITLE
your version of Docker Compose is not sufficiently recent

### ISSUE THREAD

**Issue by hansanjie** [norskvideo/media-examples#1]
i run "bash <(curl -L https://norsk.video/studio/install)"

Checking prerequisites

Norsk Studio needs a license file to operate.
You can get a FREE trial license from
https://norsk.video

Enter the path to your Norsk license file (TAB completion is available): /home/roy/Documents/license.json 
Found docker compose 2.29.7 and other required utilities, proceeding

Downloading Norsk Studio from 'https://github.com/norskvideo/norsk-studio-docker/archive/refs/tags/v1.0.383.tar.gz'
/dev/fd/63: your version of Docker Compose is not sufficiently recent - please update to the latest Docker Compose and try again

I had install latist docker compose! i do not  know why!

**Comment by adrianroe** [comment]
Many thanks for the report - a silly on our part where a check came in two halves and only one half was live.  For now we've reverted the check and will make sure that the two elements are released together in the next couple of days.
(https://github.com/norskvideo/norsk-studio-docker/commit/359bb7e613517546f9ceaa3e77c0e47efe938d29)
For now I'd recommend that you install with ```bash <(curl -L https://raw.githubusercontent.com/norskvideo/norsk-studio-docker/refs/heads/main/scripts/install)``` as Github has a habit of aggressively caching the file, so you may not get the latest using the original bash install command...

Do comment here to let us know that you are up and running - any issues and I'll arrange a quick screenshare with one of the team to make sure you are over the hump.

There will be a release in the next day or two with quality of life improvements as well (better management of session duration in particular)

**Comment by adrianroe** [comment]
@hansanjie.  Hopefully the workaround above worked for you, but there's a new release out now which changes the way installation is done to hopefully minimise the risk of a similar bug in future.  Closing.  If you have any issues with the latest install do reach out again.

Thanks for your feedback
